-- Consolidated initial schema migration.
-- Generated by combining all Drizzle migrations (0000 → 0011).
-- Use with: supabase db push
-- Or use Drizzle Kit directly: npm run db:migrate (requires DIRECT_URL)

-- ============================================================
-- 0000_init: base tables (account, session, team, user, verification, credit_pool, partner, allocations)
-- ============================================================

CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"id_token" text,
	"password" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);

CREATE TABLE "team" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"join_code" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"first_name" text,
	"last_name" text,
	"team_id" integer,
	"is_team_lead" boolean DEFAULT false NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);

CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "credit_pool" (
	"id" serial PRIMARY KEY NOT NULL,
	"partner_id" integer NOT NULL,
	"total_amount" numeric(18, 4) NOT NULL,
	"target_type" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "participant_credit_allocation" (
	"id" serial PRIMARY KEY NOT NULL,
	"credit_pool_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"amount" numeric(18, 4) NOT NULL,
	"status" text DEFAULT 'assigned' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "partner" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "team_credit_allocation" (
	"id" serial PRIMARY KEY NOT NULL,
	"credit_pool_id" integer NOT NULL,
	"team_id" integer NOT NULL,
	"amount" numeric(18, 4) NOT NULL,
	"status" text DEFAULT 'assigned' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "user" ADD CONSTRAINT "user_team_id_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "credit_pool" ADD CONSTRAINT "credit_pool_partner_id_partner_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partner"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "participant_credit_allocation" ADD CONSTRAINT "participant_credit_allocation_credit_pool_id_credit_pool_id_fk" FOREIGN KEY ("credit_pool_id") REFERENCES "public"."credit_pool"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "participant_credit_allocation" ADD CONSTRAINT "participant_credit_allocation_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team_credit_allocation" ADD CONSTRAINT "team_credit_allocation_credit_pool_id_credit_pool_id_fk" FOREIGN KEY ("credit_pool_id") REFERENCES "public"."credit_pool"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team_credit_allocation" ADD CONSTRAINT "team_credit_allocation_team_id_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE cascade ON UPDATE no action;

CREATE INDEX "account_user_id_idx" ON "account" USING btree ("user_id");
CREATE INDEX "account_provider_account_idx" ON "account" USING btree ("provider_id","account_id");
CREATE INDEX "session_user_id_idx" ON "session" USING btree ("user_id");
CREATE INDEX "credit_pool_partner_id_idx" ON "credit_pool" USING btree ("partner_id");
CREATE INDEX "participant_credit_allocation_pool_idx" ON "participant_credit_allocation" USING btree ("credit_pool_id");
CREATE INDEX "participant_credit_allocation_user_idx" ON "participant_credit_allocation" USING btree ("user_id");
CREATE INDEX "team_credit_allocation_pool_idx" ON "team_credit_allocation" USING btree ("credit_pool_id");
CREATE INDEX "team_credit_allocation_team_idx" ON "team_credit_allocation" USING btree ("team_id");

-- ============================================================
-- 0001: team_status, user_role, team_member_role enums; two_factor, team_invite, team_member tables; role/2fa columns
-- ============================================================

CREATE TYPE "public"."team_status" AS ENUM('active', 'archived');
CREATE TYPE "public"."user_role" AS ENUM('participant', 'moderator', 'reviewer', 'super_admin');
CREATE TYPE "public"."team_member_role" AS ENUM('lead', 'member');

CREATE TABLE "two_factor" (
	"id" text PRIMARY KEY NOT NULL,
	"secret" text NOT NULL,
	"backup_codes" text NOT NULL,
	"user_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "team_invite" (
	"id" text PRIMARY KEY NOT NULL,
	"team_id" integer NOT NULL,
	"code" text NOT NULL,
	"created_by_user_id" text,
	"expires_at" timestamp with time zone,
	"max_uses" integer,
	"used_count" integer DEFAULT 0 NOT NULL,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "team_invite_max_uses_check" CHECK ("team_invite"."max_uses" is null or "team_invite"."max_uses" > 0),
	CONSTRAINT "team_invite_used_count_check" CHECK ("team_invite"."used_count" >= 0)
);

CREATE TABLE "team_member" (
	"id" text PRIMARY KEY NOT NULL,
	"team_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"role" "team_member_role" DEFAULT 'member' NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	"left_at" timestamp with time zone,
	"removed_by_user_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "team" ADD COLUMN "description" text;
ALTER TABLE "team" ADD COLUMN "status" "team_status" DEFAULT 'active' NOT NULL;
ALTER TABLE "team" ADD COLUMN "member_count" integer DEFAULT 0 NOT NULL;
ALTER TABLE "team" ADD COLUMN "max_members" integer DEFAULT 5 NOT NULL;
ALTER TABLE "team" ADD COLUMN "created_by_user_id" text;
ALTER TABLE "team" ADD COLUMN "archived_at" timestamp with time zone;
ALTER TABLE "user" ADD COLUMN "role" "user_role" DEFAULT 'participant' NOT NULL;
ALTER TABLE "user" ADD COLUMN "two_factor_enabled" boolean DEFAULT false NOT NULL;

ALTER TABLE "two_factor" ADD CONSTRAINT "two_factor_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team_invite" ADD CONSTRAINT "team_invite_team_id_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team_invite" ADD CONSTRAINT "team_invite_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "team_member" ADD CONSTRAINT "team_member_team_id_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team_member" ADD CONSTRAINT "team_member_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team_member" ADD CONSTRAINT "team_member_removed_by_user_id_user_id_fk" FOREIGN KEY ("removed_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "team" ADD CONSTRAINT "team_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "team" ADD CONSTRAINT "team_member_count_range_check" CHECK ("team"."member_count" >= 0 and "team"."member_count" <= "team"."max_members");
ALTER TABLE "team" ADD CONSTRAINT "team_max_members_limit_check" CHECK ("team"."max_members" > 0 and "team"."max_members" <= 5);

CREATE UNIQUE INDEX "two_factor_user_id_unique" ON "two_factor" USING btree ("user_id");
CREATE INDEX "two_factor_secret_idx" ON "two_factor" USING btree ("secret");
CREATE UNIQUE INDEX "team_invite_code_unique" ON "team_invite" USING btree ("code");
CREATE INDEX "team_invite_team_id_idx" ON "team_invite" USING btree ("team_id");
CREATE INDEX "team_invite_revoked_at_idx" ON "team_invite" USING btree ("revoked_at");
CREATE UNIQUE INDEX "team_member_user_active_unique" ON "team_member" USING btree ("user_id") WHERE "team_member"."left_at" is null;
CREATE UNIQUE INDEX "team_member_team_lead_active_unique" ON "team_member" USING btree ("team_id") WHERE "team_member"."left_at" is null and "team_member"."role" = 'lead';
CREATE INDEX "team_member_team_active_idx" ON "team_member" USING btree ("team_id","left_at");
CREATE INDEX "team_member_user_idx" ON "team_member" USING btree ("user_id");
CREATE UNIQUE INDEX "team_join_code_unique" ON "team" USING btree ("join_code");
CREATE INDEX "team_status_idx" ON "team" USING btree ("status");
CREATE INDEX "team_created_by_user_id_idx" ON "team" USING btree ("created_by_user_id");
CREATE INDEX "user_team_id_idx" ON "user" USING btree ("team_id");
CREATE INDEX "user_role_idx" ON "user" USING btree ("role");

-- ============================================================
-- 0002: credit_redemption_link; credit_pool/partner columns
-- ============================================================

CREATE TABLE "credit_redemption_link" (
	"id" serial PRIMARY KEY NOT NULL,
	"team_allocation_id" integer,
	"participant_allocation_id" integer,
	"short_code" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "credit_pool" ADD COLUMN "created_by_user_id" text;
ALTER TABLE "credit_pool" ADD COLUMN "distributed_at" timestamp with time zone;
ALTER TABLE "credit_pool" ADD COLUMN "distributed_by_user_id" text;
ALTER TABLE "partner" ADD COLUMN "redeem_base_url" text;

ALTER TABLE "credit_redemption_link" ADD CONSTRAINT "credit_redemption_link_team_allocation_id_team_credit_allocation_id_fk" FOREIGN KEY ("team_allocation_id") REFERENCES "public"."team_credit_allocation"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "credit_redemption_link" ADD CONSTRAINT "credit_redemption_link_participant_allocation_id_participant_credit_allocation_id_fk" FOREIGN KEY ("participant_allocation_id") REFERENCES "public"."participant_credit_allocation"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "credit_pool" ADD CONSTRAINT "credit_pool_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "credit_pool" ADD CONSTRAINT "credit_pool_distributed_by_user_id_user_id_fk" FOREIGN KEY ("distributed_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;

CREATE UNIQUE INDEX "credit_redemption_link_short_code_unique" ON "credit_redemption_link" USING btree ("short_code");
CREATE INDEX "credit_redemption_link_team_alloc_idx" ON "credit_redemption_link" USING btree ("team_allocation_id");
CREATE INDEX "credit_redemption_link_participant_alloc_idx" ON "credit_redemption_link" USING btree ("participant_allocation_id");
CREATE INDEX "credit_pool_created_by_idx" ON "credit_pool" USING btree ("created_by_user_id");

-- ============================================================
-- 0003: screening_status enum; screening tables; team/user screening columns
-- ============================================================

CREATE TYPE "public"."screening_status" AS ENUM('draft', 'submitted', 'approved', 'rejected');

CREATE TABLE "screening_answer" (
	"user_id" text NOT NULL,
	"question_id" integer NOT NULL,
	"selected_index" smallint NOT NULL,
	"is_correct" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "screening_answer_user_id_question_id_pk" PRIMARY KEY("user_id","question_id")
);

CREATE TABLE "screening_question" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "screening_question_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text,
	"options" jsonb NOT NULL,
	"correct_index" smallint NOT NULL,
	"sort_order" smallint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "team" ADD COLUMN "screening_status" "screening_status" DEFAULT 'draft' NOT NULL;
ALTER TABLE "team" ADD COLUMN "screening_video_url" text;
ALTER TABLE "team" ADD COLUMN "screening_video_storage_path" text;
ALTER TABLE "team" ADD COLUMN "screening_submitted_at" timestamp with time zone;
ALTER TABLE "team" ADD COLUMN "screening_rejected_at" timestamp with time zone;
ALTER TABLE "team" ADD COLUMN "screening_rejected_reason" text;
ALTER TABLE "team" ADD COLUMN "screening_approved_at" timestamp with time zone;
ALTER TABLE "team" ADD COLUMN "screening_approved_by_user_id" text;
ALTER TABLE "user" ADD COLUMN "onboarding_completed_at" timestamp with time zone;

ALTER TABLE "screening_answer" ADD CONSTRAINT "screening_answer_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "screening_answer" ADD CONSTRAINT "screening_answer_question_id_screening_question_id_fk" FOREIGN KEY ("question_id") REFERENCES "public"."screening_question"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team" ADD CONSTRAINT "team_screening_approved_by_user_id_user_id_fk" FOREIGN KEY ("screening_approved_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;

CREATE INDEX "screening_answer_question_idx" ON "screening_answer" USING btree ("question_id");
CREATE INDEX "screening_question_sort_order_idx" ON "screening_question" USING btree ("sort_order");
CREATE INDEX "team_screening_status_idx" ON "team" USING btree ("screening_status");

-- ============================================================
-- 0004: staff_role enum; staff_invite, staff_member tables; judge/mentor user roles
-- ============================================================

CREATE TYPE "public"."staff_role" AS ENUM('judge', 'mentor');
ALTER TYPE "public"."user_role" ADD VALUE 'judge';
ALTER TYPE "public"."user_role" ADD VALUE 'mentor';

CREATE TABLE "staff_invite" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"role" "staff_role" NOT NULL,
	"token" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_by_user_id" text,
	"accepted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "staff_member" (
	"user_id" text PRIMARY KEY NOT NULL,
	"company_name" text,
	"phone" text,
	"position" text,
	"telegram_username" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "staff_invite" ADD CONSTRAINT "staff_invite_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "staff_member" ADD CONSTRAINT "staff_member_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;

CREATE UNIQUE INDEX "staff_invite_token_unique" ON "staff_invite" USING btree ("token");
CREATE INDEX "staff_invite_email_idx" ON "staff_invite" USING btree ("email");
CREATE INDEX "staff_invite_expires_at_idx" ON "staff_invite" USING btree ("expires_at");

-- ============================================================
-- 0005: judge_score table
-- ============================================================

CREATE TABLE "judge_score" (
	"id" text PRIMARY KEY NOT NULL,
	"team_id" integer NOT NULL,
	"judge_user_id" text NOT NULL,
	"innovation" integer DEFAULT 0 NOT NULL,
	"technical_execution" integer DEFAULT 0 NOT NULL,
	"ai_usage" integer DEFAULT 0 NOT NULL,
	"ux_ui" integer DEFAULT 0 NOT NULL,
	"business_potential" integer DEFAULT 0 NOT NULL,
	"comment" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "judge_score_innovation_range" CHECK ("judge_score"."innovation" >= 0 and "judge_score"."innovation" <= 25),
	CONSTRAINT "judge_score_technical_range" CHECK ("judge_score"."technical_execution" >= 0 and "judge_score"."technical_execution" <= 25),
	CONSTRAINT "judge_score_ai_range" CHECK ("judge_score"."ai_usage" >= 0 and "judge_score"."ai_usage" <= 20),
	CONSTRAINT "judge_score_ux_range" CHECK ("judge_score"."ux_ui" >= 0 and "judge_score"."ux_ui" <= 15),
	CONSTRAINT "judge_score_business_range" CHECK ("judge_score"."business_potential" >= 0 and "judge_score"."business_potential" <= 15)
);

ALTER TABLE "judge_score" ADD CONSTRAINT "judge_score_team_id_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "judge_score" ADD CONSTRAINT "judge_score_judge_user_id_user_id_fk" FOREIGN KEY ("judge_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;

CREATE UNIQUE INDEX "judge_score_team_judge_unique" ON "judge_score" USING btree ("team_id","judge_user_id");
CREATE INDEX "judge_score_team_idx" ON "judge_score" USING btree ("team_id");
CREATE INDEX "judge_score_judge_idx" ON "judge_score" USING btree ("judge_user_id");

-- ============================================================
-- 0006: app_setting, project tables
-- ============================================================

CREATE TABLE "app_setting" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "project" (
	"id" text PRIMARY KEY NOT NULL,
	"team_id" integer NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"github_url" text NOT NULL,
	"demo_url" text,
	"tech_stack" text,
	"slides_url" text,
	"video_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "project" ADD CONSTRAINT "project_team_id_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE cascade ON UPDATE no action;

CREATE UNIQUE INDEX "project_team_id_unique" ON "project" USING btree ("team_id");
CREATE INDEX "project_created_at_idx" ON "project" USING btree ("created_at");

-- ============================================================
-- 0007: screening_phase enum; site_settings table
-- ============================================================

CREATE TYPE "public"."screening_phase" AS ENUM('registration', 'screening_active', 'screening_completed');

CREATE TABLE "site_settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ============================================================
-- 0008: credit_audit_log, credit_pending_link, credit_upload_batch tables; credit_pool/redemption_link columns; unique constraint on participant_credit_allocation
-- ============================================================

CREATE TABLE "credit_audit_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"credit_pool_id" integer NOT NULL,
	"actor_user_id" text NOT NULL,
	"action" text NOT NULL,
	"details" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "credit_pending_link" (
	"id" serial PRIMARY KEY NOT NULL,
	"credit_pool_id" integer NOT NULL,
	"upload_batch_id" text NOT NULL,
	"target_user_id" text NOT NULL,
	"full_url" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"participant_allocation_id" integer,
	"redemption_link_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "credit_upload_batch" (
	"id" text PRIMARY KEY NOT NULL,
	"credit_pool_id" integer NOT NULL,
	"uploaded_by_user_id" text NOT NULL,
	"file_name" text,
	"raw_row_count" integer NOT NULL,
	"deduped_row_count" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "credit_pool" ADD COLUMN "distribution_type" text DEFAULT 'even' NOT NULL;
ALTER TABLE "credit_pool" ADD COLUMN "general_credit_url" text;
ALTER TABLE "credit_redemption_link" ADD COLUMN "full_url" text;
ALTER TABLE "credit_redemption_link" ADD COLUMN "claimed_at" timestamp with time zone;
ALTER TABLE "credit_redemption_link" ADD COLUMN "revoked_at" timestamp with time zone;

ALTER TABLE "credit_audit_log" ADD CONSTRAINT "credit_audit_log_credit_pool_id_credit_pool_id_fk" FOREIGN KEY ("credit_pool_id") REFERENCES "public"."credit_pool"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "credit_audit_log" ADD CONSTRAINT "credit_audit_log_actor_user_id_user_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "credit_pending_link" ADD CONSTRAINT "credit_pending_link_credit_pool_id_credit_pool_id_fk" FOREIGN KEY ("credit_pool_id") REFERENCES "public"."credit_pool"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "credit_pending_link" ADD CONSTRAINT "credit_pending_link_upload_batch_id_credit_upload_batch_id_fk" FOREIGN KEY ("upload_batch_id") REFERENCES "public"."credit_upload_batch"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "credit_pending_link" ADD CONSTRAINT "credit_pending_link_target_user_id_user_id_fk" FOREIGN KEY ("target_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "credit_pending_link" ADD CONSTRAINT "credit_pending_link_participant_allocation_id_participant_credit_allocation_id_fk" FOREIGN KEY ("participant_allocation_id") REFERENCES "public"."participant_credit_allocation"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "credit_pending_link" ADD CONSTRAINT "credit_pending_link_redemption_link_id_credit_redemption_link_id_fk" FOREIGN KEY ("redemption_link_id") REFERENCES "public"."credit_redemption_link"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "credit_upload_batch" ADD CONSTRAINT "credit_upload_batch_credit_pool_id_credit_pool_id_fk" FOREIGN KEY ("credit_pool_id") REFERENCES "public"."credit_pool"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "credit_upload_batch" ADD CONSTRAINT "credit_upload_batch_uploaded_by_user_id_user_id_fk" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;

CREATE INDEX "credit_audit_log_pool_idx" ON "credit_audit_log" USING btree ("credit_pool_id");
CREATE INDEX "credit_audit_log_created_idx" ON "credit_audit_log" USING btree ("created_at");
CREATE INDEX "credit_pending_link_pool_idx" ON "credit_pending_link" USING btree ("credit_pool_id");
CREATE INDEX "credit_pending_link_batch_idx" ON "credit_pending_link" USING btree ("upload_batch_id");
CREATE INDEX "credit_pending_link_status_idx" ON "credit_pending_link" USING btree ("status");
CREATE INDEX "credit_pending_link_target_user_idx" ON "credit_pending_link" USING btree ("target_user_id");
CREATE INDEX "credit_upload_batch_pool_idx" ON "credit_upload_batch" USING btree ("credit_pool_id");
CREATE INDEX "credit_upload_batch_created_idx" ON "credit_upload_batch" USING btree ("created_at");
CREATE UNIQUE INDEX "participant_credit_allocation_pool_user_unique" ON "participant_credit_allocation" USING btree ("credit_pool_id","user_id");

-- ============================================================
-- 0009: mentor_request_status enum; mentor_request table
-- ============================================================

CREATE TYPE "public"."mentor_request_status" AS ENUM('pending', 'assigned', 'matched', 'completed', 'cancelled');

CREATE TABLE "mentor_request" (
	"id" text PRIMARY KEY NOT NULL,
	"team_id" integer NOT NULL,
	"status" "mentor_request_status" DEFAULT 'pending' NOT NULL,
	"assigned_mentor_id" text,
	"accepted_mentor_id" text,
	"declined_mentor_ids" text[] DEFAULT '{}' NOT NULL,
	"requested_at" timestamp with time zone DEFAULT now() NOT NULL,
	"assigned_at" timestamp with time zone,
	"matched_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone
);

ALTER TABLE "mentor_request" ADD CONSTRAINT "mentor_request_team_id_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "mentor_request" ADD CONSTRAINT "mentor_request_assigned_mentor_id_user_id_fk" FOREIGN KEY ("assigned_mentor_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "mentor_request" ADD CONSTRAINT "mentor_request_accepted_mentor_id_user_id_fk" FOREIGN KEY ("accepted_mentor_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;

CREATE INDEX "mentor_request_team_idx" ON "mentor_request" USING btree ("team_id");
CREATE INDEX "mentor_request_status_idx" ON "mentor_request" USING btree ("status");
CREATE INDEX "mentor_request_assigned_mentor_idx" ON "mentor_request" USING btree ("assigned_mentor_id");
CREATE INDEX "mentor_request_accepted_mentor_idx" ON "mentor_request" USING btree ("accepted_mentor_id");

-- ============================================================
-- 0010: team scoring adjustment columns
-- ============================================================

ALTER TABLE "team" ADD COLUMN "judge_count_override" integer;
ALTER TABLE "team" ADD COLUMN "late_submission_penalty_points" integer DEFAULT 0 NOT NULL;
ALTER TABLE "team" ADD CONSTRAINT "team_judge_count_override_check" CHECK ("team"."judge_count_override" is null or ("team"."judge_count_override" >= 1 and "team"."judge_count_override" <= 100));
ALTER TABLE "team" ADD CONSTRAINT "team_late_penalty_range_check" CHECK ("team"."late_submission_penalty_points" >= 0 and "team"."late_submission_penalty_points" <= 100);

-- ============================================================
-- 0011: team final_score_override column
-- ============================================================

ALTER TABLE "team" ADD COLUMN "final_score_override" real;
ALTER TABLE "team" ADD CONSTRAINT "team_final_score_override_range_check" CHECK ("team"."final_score_override" is null or ("team"."final_score_override" >= 0 and "team"."final_score_override" <= 100));
